-- Create flight_schedules table
create table if not exists flight_schedules (
    id bigint generated by default as identity primary key,
    flight_number text not null,
    departure text not null,
    arrival text not null,
    aircraft text not null,
    departure_time text not null, -- "HH:MM"
    arrival_time text not null,   -- "HH:MM"
    days text,                    -- "1234567"
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Separate index for upsert performance
create index if not exists idx_flight_schedules_flight_number on flight_schedules(flight_number);

-- Enable RLS
alter table flight_schedules enable row level security;

-- Policies (Public read, Service Role write)
create policy "Public read access" on flight_schedules for select using (true);
create policy "Service role full access" on flight_schedules using (auth.role() = 'service_role');
